# Generated by Django 6.0.2 on 2026-02-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('experience_year', models.PositiveSmallIntegerField(default=0)),
                ('salary', models.PositiveBigIntegerField(default=0)),
                ('groups_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.AlterModelOptions(
            name='universitet',
            options={'ordering': ['created_at', 'nom'], 'verbose_name': 'Universitet', 'verbose_name_plural': 'Universitetlar'},
        ),
    ]
