# Generated by Django 6.0.2 on 2026-02-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0002_teacher_alter_universitet_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatar/')),
                ('gpa', models.FloatField(default=0)),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
