# Generated by Django 6.0.2 on 2026-02-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0003_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('founded_year', models.SmallIntegerField(default=0, null=True)),
                ('owner_name', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
