# Generated by Django 6.0.2 on 2026-02-27 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0004_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['company_name', 'founded_year'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
    ]
