# Generated by Django 6.0.2 on 2026-02-28 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darslik', '0007_alter_group_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDavomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baho', models.IntegerField(choices=[(5, '5-baho'), (4, '4-baho'), (3, '3-baho'), (2, '2-baho'), (1, '1-baho'), (0, '0-baho')], default=0)),
                ('status', models.CharField(choices=[('keldi', 'keldi'), ('online', 'Online Qatnashdi'), ('sababli', 'Sababli kelmagan'), ('yoq', 'Darsga kelmagan')], default='keldi', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darslik.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='darslik.teacher')),
            ],
        ),
    ]
