# Generated by Django 6.0.2 on 2026-02-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('darslik', '0008_studentdavomat'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuTestModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_nom', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darslik.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darslik.teacher')),
            ],
        ),
    ]
