# Generated by Django 6.0.2 on 2026-02-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('avto', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='salom.avto')),
            ],
        ),
    ]
