# Generated by Django 6.0.2 on 2026-02-28 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('darslik', '0008_studentdavomat'),
        ('zor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='butestmodel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zor.butestmodel'),
        ),
        migrations.AddField(
            model_name='company',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='darslik.student'),
        ),
        migrations.AddField(
            model_name='company',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darslik.teacher'),
        ),
        migrations.AddField(
            model_name='company',
            name='unversitet',
            field=models.ManyToManyField(blank=True, to='darslik.universitet'),
        ),
    ]
